play_low_left_run=image/MetalSlug/MetalSlug/images/plays/run10.png;image/MetalSlug/MetalSlug/images/plays/run20.png;image/MetalSlug/MetalSlug/images/plays/run30.png;image/MetalSlug/MetalSlug/images/plays/run40.png;image/MetalSlug/MetalSlug/images/plays/run50.png;image/MetalSlug/MetalSlug/images/plays/run60.png;image/MetalSlug/MetalSlug/images/plays/run70.png;image/MetalSlug/MetalSlug/images/plays/run80.png;
play_low_right_run=image/MetalSlug/MetalSlug/images/plays/run11.png;image/MetalSlug/MetalSlug/images/plays/run21.png;image/MetalSlug/MetalSlug/images/plays/run31.png;image/MetalSlug/MetalSlug/images/plays/run41.png;image/MetalSlug/MetalSlug/images/plays/run51.png;image/MetalSlug/MetalSlug/images/plays/run61.png;image/MetalSlug/MetalSlug/images/plays/run71.png;image/MetalSlug/MetalSlug/images/plays/run81.png;

play_low_left_squat=image/MetalSlug/MetalSlug/images/plays/squat_run00.png;image/MetalSlug/MetalSlug/images/plays/squat_run10.png;image/MetalSlug/MetalSlug/images/plays/squat_run20.png;image/MetalSlug/MetalSlug/images/plays/squat_run30.png;image/MetalSlug/MetalSlug/images/plays/squat_run40.png;
play_low_right_squat=image/MetalSlug/MetalSlug/images/plays/squat_run01.png;image/MetalSlug/MetalSlug/images/plays/squat_run11.png;image/MetalSlug/MetalSlug/images/plays/squat_run21.png;image/MetalSlug/MetalSlug/images/plays/squat_run31.png;image/MetalSlug/MetalSlug/images/plays/squat_run41.png;

enemy_left_rifle_run=image/MetalSlug/MetalSlug/images/Enemy/L/enemy_run100.png;image/MetalSlug/MetalSlug/images/Enemy/L/enemy_run110.png;image/MetalSlug/MetalSlug/images/Enemy/L/enemy_run120.png;image/MetalSlug/MetalSlug/images/Enemy/L/enemy_run130.png;image/MetalSlug/MetalSlug/images/Enemy/L/enemy_run140.png;
enemy_right_rifle_run=image/MetalSlug/MetalSlug/images/Enemy/L/enemy_run101.png;image/MetalSlug/MetalSlug/images/Enemy/L/enemy_run111.png;image/MetalSlug/MetalSlug/images/Enemy/L/enemy_run121.png;image/MetalSlug/MetalSlug/images/Enemy/L/enemy_run131.png;image/MetalSlug/MetalSlug/images/Enemy/L/enemy_run141.png;

enemy_left_bazooka_run=image/MetalSlug/MetalSlug/images/Enemy/L/enemy_run200.png;image/MetalSlug/MetalSlug/images/Enemy/L/enemy_run210.png;image/MetalSlug/MetalSlug/images/Enemy/L/enemy_run220.png;image/MetalSlug/MetalSlug/images/Enemy/L/enemy_run230.png;image/MetalSlug/MetalSlug/images/Enemy/L/enemy_run240.png;
enemy_right_bazooka_run=image/MetalSlug/MetalSlug/images/Enemy/L/enemy_run201.png;image/MetalSlug/MetalSlug/images/Enemy/L/enemy_run211.png;image/MetalSlug/MetalSlug/images/Enemy/L/enemy_run221.png;image/MetalSlug/MetalSlug/images/Enemy/L/enemy_run231.png;image/MetalSlug/MetalSlug/images/Enemy/L/enemy_run241.png;

enemy_left_rifle_die=image/MetalSlug/MetalSlug/images/Enemy/20070130041731OFQDOJuj-231.png;image/MetalSlug/MetalSlug/images/Enemy/20070130041731OFQDOJuj-232.png;image/MetalSlug/MetalSlug/images/Enemy/20070130041731OFQDOJuj-233.png;image/MetalSlug/MetalSlug/images/Enemy/20070130041731OFQDOJuj-234.png;image/MetalSlug/MetalSlug/images/Enemy/20070130041731OFQDOJuj-235.png;
enemy_left_bazooka_die=image/MetalSlug/MetalSlug/images/Enemy/20070130041731OFQDOJuj-231.png;image/MetalSlug/MetalSlug/images/Enemy/20070130041731OFQDOJuj-232.png;image/MetalSlug/MetalSlug/images/Enemy/20070130041731OFQDOJuj-233.png;image/MetalSlug/MetalSlug/images/Enemy/20070130041731OFQDOJuj-234.png;image/MetalSlug/MetalSlug/images/Enemy/20070130041731OFQDOJuj-235.png;


hostage_left_trapped=image/MetalSlug/MetalSlug/images/hostage/oder0.png;image/MetalSlug/MetalSlug/images/hostage/oder1.png;image/MetalSlug/MetalSlug/images/hostage/oder2.png;image/MetalSlug/MetalSlug/images/hostage/oder3.png;image/MetalSlug/MetalSlug/images/hostage/oder4.png;image/MetalSlug/MetalSlug/images/hostage/oder5.png;image/MetalSlug/MetalSlug/images/hostage/oder6.png;image/MetalSlug/MetalSlug/images/hostage/oder7.png;image/MetalSlug/MetalSlug/images/hostage/oder8.png;image/MetalSlug/MetalSlug/images/hostage/oder8.png;
hostage_right_trapped=image/MetalSlug/MetalSlug/images/hostage/oder0.png;image/MetalSlug/MetalSlug/images/hostage/oder1.png;image/MetalSlug/MetalSlug/images/hostage/oder2.png;image/MetalSlug/MetalSlug/images/hostage/oder3.png;image/MetalSlug/MetalSlug/images/hostage/oder4.png;image/MetalSlug/MetalSlug/images/hostage/oder5.png;image/MetalSlug/MetalSlug/images/hostage/oder6.png;image/MetalSlug/MetalSlug/images/hostage/oder7.png;image/MetalSlug/MetalSlug/images/hostage/oder8.png;image/MetalSlug/MetalSlug/images/hostage/oder8.png;

hostage_left_resecured=image/MetalSlug/MetalSlug/images/hostage/oder31.png;image/MetalSlug/MetalSlug/images/hostage/oder32.png;image/MetalSlug/MetalSlug/images/hostage/oder33.png;image/MetalSlug/MetalSlug/images/hostage/oder34.png;image/MetalSlug/MetalSlug/images/hostage/oder35.png;image/MetalSlug/MetalSlug/images/hostage/oder36.png;image/MetalSlug/MetalSlug/images/hostage/oder37.png;
hostage_right_resecured=image/MetalSlug/MetalSlug/images/hostage/oder31.png;image/MetalSlug/MetalSlug/images/hostage/oder32.png;image/MetalSlug/MetalSlug/images/hostage/oder33.png;image/MetalSlug/MetalSlug/images/hostage/oder34.png;image/MetalSlug/MetalSlug/images/hostage/oder35.png;image/MetalSlug/MetalSlug/images/hostage/oder36.png;image/MetalSlug/MetalSlug/images/hostage/oder37.png;

missile_bang=image/MetalSlug/MetalSlug/images/bang/bomb_bang0.png;image/MetalSlug/MetalSlug/images/bang/bomb_bang1.png;image/MetalSlug/MetalSlug/images/bang/bomb_bang2.png;image/MetalSlug/MetalSlug/images/bang/bomb_bang3.png;image/MetalSlug/MetalSlug/images/bang/bomb_bang4.png;image/MetalSlug/MetalSlug/images/bang/bomb_bang5.png;image/MetalSlug/MetalSlug/images/bang/bomb_bang6.png;image/MetalSlug/MetalSlug/images/bang/bomb_bang7.png;image/MetalSlug/MetalSlug/images/bang/bomb_bang8.png;image/MetalSlug/MetalSlug/images/bang/bomb_bang9.png;image/MetalSlug/MetalSlug/images/bang/bomb_bang10.png;image/MetalSlug/MetalSlug/images/bang/bomb_bang11.png;image/MetalSlug/MetalSlug/images/bang/bomb_bang12.png;image/MetalSlug/MetalSlug/images/bang/bomb_bang13.png;image/MetalSlug/MetalSlug/images/bang/bomb_bang14.png;image/MetalSlug/MetalSlug/images/bang/bomb_bang15.png;image/MetalSlug/MetalSlug/images/bang/bomb_bang16.png;

boss_run=image/MetalSlug/MetalSlug/images/boss/D_boss(1).png;image/MetalSlug/MetalSlug/images/boss/D_boss(2).png;image/MetalSlug/MetalSlug/images/boss/D_boss(3).png;image/MetalSlug/MetalSlug/images/boss/D_boss(4).png;image/MetalSlug/MetalSlug/images/boss/D_boss(5).png;image/MetalSlug/MetalSlug/images/boss/D_boss(6).png;image/MetalSlug/MetalSlug/images/boss/D_boss(7).png;image/MetalSlug/MetalSlug/images/boss/D_boss(8).png;image/MetalSlug/MetalSlug/images/boss/D_boss(9).png;image/MetalSlug/MetalSlug/images/boss/D_boss(10).png;image/MetalSlug/MetalSlug/images/boss/D_boss(11).png;image/MetalSlug/MetalSlug/images/boss/D_boss(12).png;image/MetalSlug/MetalSlug/images/boss/D_boss(13).png;image/MetalSlug/MetalSlug/images/boss/D_boss(14).png;image/MetalSlug/MetalSlug/images/boss/D_boss(15).png;image/MetalSlug/MetalSlug/images/boss/D_boss(16).png;
